#!/bin/sh

# write the ssh key.
mkdir /root/.ssh
echo -n "KEY: $SSH_KEY"
echo -n "$SSH_KEY" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa

# add github.com to our known hosts.
touch /root/.ssh/known_hosts
chmod 600 /root/.ssh/known_hosts
ssh-keyscan -H gin.g-node.org > /etc/ssh/ssh_known_hosts 2> /dev/null